name: Check Windows build image

on:
  pull_request:
    paths:
      - 'tools/build-image/windows/**'

permissions:
  contents: read

jobs:
  check-windows-build-image:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Create test Windows build image
        uses: mr-smithers-excellent/docker-build-push@16094d9627df93cfe14f2d51d0c4a501d57aa0ab # v6.6
        with:
          image: grafana/alloy-build-image
          tags: latest
          registry: docker.io
          pushImage: false
          dockerfile: ./tools/build-image/windows/Dockerfile
